#!/bin/sh
# This script is used to generate
# configuration files. It is relatively
# hardcoded
#
set -e

rm -f gnulib/lib/* gnulib/m4/*
PATH=/usr/local/src/gnu/gnulib:${PATH}
gnulib-tool --source-base=gnulib/lib --m4-base=gnulib/m4 --import \
	close getopt nanosleep printf-posix
exec autoreconf
