#!/bin/sh
# This script is used to generate
# configuration files. It is relatively
# hardcoded
#
set -e

PATH=/usr/local/src/gnu/gnulib:${PATH}
gnulib-tool --source-base=gnulib/lib --m4-base=gnulib/m4 --import \
	getopt nanosleep
exec autoreconf
